nav:
    - OpenAPI 文档:
        - OpenAPI 文档索引: openapi/index.md
        - 应用工作台 OpenAPI:
            - v0.117.x:
                - v0.117.0: openapi/amamba/v0.117.0.md
                - v0.117.1: openapi/amamba/v0.117.1.md
            - v0.116.0: openapi/amamba/v0.116.0.md
            - v0.115.0: openapi/amamba/v0.115.0.md
            - v0.114.0: openapi/amamba/v0.114.0.md
            - v0.113.x:
                - v0.113.0: openapi/amamba/v0.113.0.md
                - v0.113.1: openapi/amamba/v0.113.1.md
                - v0.113.2: openapi/amamba/v0.113.2.md
                - v0.113.3: openapi/amamba/v0.113.3.md
            - v0.112.0: openapi/amamba/v0.112.0.md
            - v0.111.x:
                - v0.111.0: openapi/amamba/v0.111.0.md
                - v0.111.2: openapi/amamba/v0.111.2.md
            - v0.110.0: openapi/amamba/v0.110.0.md
            - v0.109.1: openapi/amamba/v0.109.1.md
        - 容器管理 OpenAPI:
            - v0.25.x:
                - v0.25.0: openapi/kpanda/v0.25.0.md
                - v0.25.1: openapi/kpanda/v0.25.1.md
            - v0.23.0: openapi/kpanda/v0.23.0.md
            - v0.21.1: openapi/kpanda/v0.21.1.md
            - v0.20.x: 
                - v0.20.0: openapi/kpanda/v0.20.0.md
                - v0.20.1: openapi/kpanda/v0.20.1.md
            - v0.19.0: openapi/kpanda/v0.19.0.md
            - v0.18.x:
                - v0.18.0: openapi/kpanda/v0.18.0.md
                - v0.18.1: openapi/kpanda/v0.18.1.md
        - 虚拟机 OpenAPI:
            - v0.6.0: openapi/virtnest/v0.6.0.md
        - 多云编排 OpenAPI:
            - v0.17.0: openapi/kairship/v0.17.0.md
            - v0.16.0: openapi/kairship/v0.16.0.md
            - v0.15.0: openapi/kairship/v0.15.0.md
            - v0.14.0: openapi/kairship/v0.14.0.md
            - v0.13.x:
                - v0.13.0: openapi/kairship/v0.13.0.md
                - v0.13.1: openapi/kairship/v0.13.1.md
            - v0.12.0: openapi/kairship/v0.12.0.md
            - v0.11.x:
                - v0.11.0: openapi/kairship/v0.11.0.md
                - v0.11.1: openapi/kairship/v0.11.1.md
            - v0.10.x:
                - v0.10.0: openapi/kairship/v0.10.0.md
                - v0.10.1: openapi/kairship/v0.10.1.md
                - v0.10.2: openapi/kairship/v0.10.2.md
                - v0.10.3: openapi/kairship/v0.10.3.md
            - v0.9.0: openapi/kairship/v0.9.0.md
            - v0.8.0: openapi/kairship/v0.8.0.md
        - 镜像仓库 OpenAPI:
            - v0.15.0: openapi/kangaroo/v0.15.0.md
            - v0.14.0: openapi/kangaroo/v0.14.0.md
            - v0.13.x:
                - v0.13.0: openapi/kangaroo/v0.13.0.md
                - v0.13.1: openapi/kangaroo/v0.13.1.md 
            - v0.12.x:
                - v0.12.0: openapi/kangaroo/v0.12.0.md
                - v0.12.1: openapi/kangaroo/v0.12.1.md
            - v0.11.0: openapi/kangaroo/v0.11.0.md
            - v0.10.x:
                - v0.10.0: openapi/kangaroo/v0.10.0.md
                - v0.10.1: openapi/kangaroo/v0.10.1.md
            - v0.9.1: openapi/kangaroo/v0.9.1.md
            - v0.8.0: openapi/kangaroo/v0.8.0.md
        - 网络 OpenAPI:
            - v0.13.0: openapi/spidernet/v0.13.0.md
            - v0.12.x: openapi/spidernet/v0.12.0.md
            - v0.10.x:
                - v0.10.0: openapi/spidernet/v0.10.0.md
                - v0.10.1: openapi/spidernet/v0.10.1.md
            - v0.9.0: openapi/spidernet/v0.9.0.md
            - v0.8.x:
                - v0.8.0: openapi/spidernet/v0.8.0.md
                - v0.8.1: openapi/spidernet/v0.8.1.md
            - v0.7.0: openapi/spidernet/v0.7.0.md
            - v0.6.0: openapi/spidernet/v0.6.0.md
            - v0.5.0: openapi/spidernet/v0.5.0.md
        - 可观测性 OpenAPI:
            - v0.24.0: openapi/insight/v0.24.0.md
            - v0.23.1: openapi/insight/v0.23.1.md
            - v0.22.x:
                - v0.22.0: openapi/insight/v0.22.0.md
                - v0.22.1: openapi/insight/v0.22.1.md
            - v0.21.x:
                - v0.21.0: openapi/insight/v0.21.0.md
                - v0.21.1: openapi/insight/v0.21.1.md
                - v0.21.2: openapi/insight/v0.21.2.md
            - v0.20.0: openapi/insight/v0.20.0.md
            - v0.19.x:
                - v0.19.0: openapi/insight/v0.19.0.md
                - v0.19.1: openapi/insight/v0.19.1.md
                - v0.19.2: openapi/insight/v0.19.2.md
            - v0.18.x:
                - v0.18.0: openapi/insight/v0.18.0.md
                - v0.18.1: openapi/insight/v0.18.1.md
                - v0.18.2: openapi/insight/v0.18.2.md
            - v0.17.x:
                - v0.17.0: openapi/insight/v0.17.0.md
                - v0.17.1: openapi/insight/v0.17.1.md
                - v0.17.2: openapi/insight/v0.17.2.md
                - v0.17.3: openapi/insight/v0.17.3.md
            - v0.16.0: openapi/insight/v0.16.0.md
        - 微服务引擎 OpenAPI:
            - v0.35.0: openapi/skoala/v0.35.0.md
            - v0.34.0: openapi/skoala/v0.34.0.md
            - v0.33.x:
                - v0.33.0: openapi/skoala/v0.33.0.md
                - v0.33.1: openapi/skoala/v0.33.1.md
                - v0.33.2: openapi/skoala/v0.33.2.md
                - v0.33.3: openapi/skoala/v0.33.3.md
            - v0.32.0: openapi/skoala/v0.32.0.md
            - v0.31.2: openapi/skoala/v0.31.2.md
            - v0.30.0: openapi/skoala/v0.30.0.md
            - v0.29.0: openapi/skoala/v0.29.0.md
            - v0.28.x:
                - v0.28.0: openapi/skoala/v0.28.0.md
                - v0.28.1: openapi/skoala/v0.28.1.md
            - v0.27.x:
                - v0.27.0: openapi/skoala/v0.27.0.md
                - v0.27.1: openapi/skoala/v0.27.1.md
                - v0.27.2: openapi/skoala/v0.27.2.md
            - v0.26.x:
                - v0.26.0: openapi/skoala/v0.26.0.md
                - v0.26.1: openapi/skoala/v0.26.1.md
                - v0.26.2: openapi/skoala/v0.26.2.md
            - v0.25.0: openapi/skoala/v0.25.0.md
            - v0.24.x:
                - v0.24.0: openapi/skoala/v0.24.0.md
                - v0.24.1: openapi/skoala/v0.24.1.md
            - v0.23.0: openapi/skoala/v0.23.0.md
            - v0.22.x:
                - v0.22.1: openapi/skoala/v0.22.1.md
                - v0.22.2: openapi/skoala/v0.22.2.md
        - 服务网格 OpenAPI:
            - v0.109.0: openapi/mspider/v0.109.0.md
            - v0.108.3: openapi/mspider/v0.108.3.md
            - v0.106.2: openapi/mspider/v0.106.2.md
            - v0.105.1: openapi/mspider/v0.105.1.md
        - 中间件 OpenAPI:
            - Index: openapi/midware.md
            - Elasticsearch 搜索服务:
                - v0.14.0: openapi/mcamel/elasticsearch/elasticsearch-v0.14.0.md
                - v0.13.0: openapi/mcamel/elasticsearch/elasticsearch-v0.13.0.md
                - v0.12.0: openapi/mcamel/elasticsearch/elasticsearch-v0.12.0.md
                - v0.11.0: openapi/mcamel/elasticsearch/elasticsearch-v0.11.0.md
                - v0.10.x:
                    - v0.10.0: openapi/mcamel/elasticsearch/elasticsearch-v0.10.0.md
                    - v0.10.1: openapi/mcamel/elasticsearch/elasticsearch-v0.10.1.md
                - v0.9.x:
                    - v0.9.0: openapi/mcamel/elasticsearch/elasticsearch-v0.9.0.md
                    - v0.9.1: openapi/mcamel/elasticsearch/elasticsearch-v0.9.1.md
                    - v0.9.2: openapi/mcamel/elasticsearch/elasticsearch-v0.9.2.md
                    - v0.9.3: openapi/mcamel/elasticsearch/elasticsearch-v0.9.3.md
                - v0.8.0: openapi/mcamel/elasticsearch/elasticsearch-v0.8.0.md
                - v0.7.x:
                    - v0.7.0: openapi/mcamel/elasticsearch/elasticsearch-v0.7.0.md
                    - v0.7.1: openapi/mcamel/elasticsearch/elasticsearch-v0.7.1.md
            - Kafka 消息队列:
                - v0.12.0: openapi/mcamel/kafka/kafka-v0.12.0.md
                - v0.11.x:
                    - v0.11.0: openapi/mcamel/kafka/kafka-v0.11.0.md
                    - v0.11.1: openapi/mcamel/kafka/kafka-v0.11.1.md
                    - v0.11.2: openapi/mcamel/kafka/kafka-v0.11.2.md
                - v0.10.0: openapi/mcamel/kafka/kafka-v0.10.0.md
                - v0.9.0: openapi/mcamel/kafka/kafka-v0.9.0.md
                - v0.8.x:
                    - v0.8.0: openapi/mcamel/kafka/kafka-v0.8.0.md
                    - v0.8.1: openapi/mcamel/kafka/kafka-v0.8.1.md
                - v0.7.x:
                    - v0.7.3: openapi/mcamel/kafka/kafka-v0.7.3.md
                    - v0.7.2: openapi/mcamel/kafka/kafka-v0.7.2.md
                    - v0.7.1: openapi/mcamel/kafka/kafka-v0.7.1.md
                    - v0.7.0: openapi/mcamel/kafka/kafka-v0.7.0.md
                - v0.6.0: openapi/mcamel/kafka/kafka-v0.6.0.md
                - v0.5.x:
                    - v0.5.0: openapi/mcamel/kafka/kafka-v0.5.0.md
                    - v0.5.1: openapi/mcamel/kafka/kafka-v0.5.1.md
            - RabbitMQ 消息队列:
                - v0.17.0: openapi/mcamel/rabbitmq/rabbitmq-v0.17.0.md
                - v0.16.0: openapi/mcamel/rabbitmq/rabbitmq-v0.16.0.md
                - v0.15.0: openapi/mcamel/rabbitmq/rabbitmq-v0.15.0.md
                - v0.14.0: openapi/mcamel/rabbitmq/rabbitmq-v0.14.0.md
                - v0.13.x:
                    - v0.13.0: openapi/mcamel/rabbitmq/rabbitmq-v0.13.0.md
                    - v0.13.1: openapi/mcamel/rabbitmq/rabbitmq-v0.13.1.md
                - v0.12.x:
                    - v0.12.0: openapi/mcamel/rabbitmq/rabbitmq-v0.12.0.md
                    - v0.12.1: openapi/mcamel/rabbitmq/rabbitmq-v0.12.1.md
                    - v0.12.2: openapi/mcamel/rabbitmq/rabbitmq-v0.12.2.md
                    - v0.12.3: openapi/mcamel/rabbitmq/rabbitmq-v0.12.3.md
                - v0.11.0: openapi/mcamel/rabbitmq/rabbitmq-v0.11.0.md
                - v0.10.x:
                    - v0.10.0: openapi/mcamel/rabbitmq/rabbitmq-v0.10.0.md
                    - v0.10.1: openapi/mcamel/rabbitmq/rabbitmq-v0.10.1.md
            - RocketMQ 消息队列:
                - v0.4.0: openapi/mcamel/rocketmq/rocketmq-v0.4.0.md
                - v0.3.0: openapi/mcamel/rocketmq/rocketmq-v0.3.0.md
                - v0.2.0: openapi/mcamel/rocketmq/rocketmq-v0.2.0.md
                - v0.1.1: openapi/mcamel/rocketmq/rocketmq-v0.1.1.md
            - MinIO 对象存储:
                - v0.12.0: openapi/mcamel/minio/minio-v0.12.0.md
                - v0.11.0: openapi/mcamel/minio/minio-v0.11.0.md
                - v0.10.0: openapi/mcamel/minio/minio-v0.10.0.md
                - v0.9.0: openapi/mcamel/minio/minio-v0.9.0.md
                - v0.8.x:
                    - v0.8.0: openapi/mcamel/minio/minio-v0.8.0.md
                    - v0.8.1: openapi/mcamel/minio/minio-v0.8.1.md
                - v0.7.x:
                    - v0.7.3: openapi/mcamel/minio/minio-v0.7.3.md
                    - v0.7.2: openapi/mcamel/minio/minio-v0.7.2.md
                    - v0.7.1: openapi/mcamel/minio/minio-v0.7.1.md
                    - v0.7.0: openapi/mcamel/minio/minio-v0.7.0.md
                - v0.6.0: openapi/mcamel/minio/minio-v0.6.0.md
                - v0.5.x:
                    - v0.5.0: openapi/mcamel/minio/minio-v0.5.0.md
                    - v0.5.1: openapi/mcamel/minio/minio-v0.5.1.md
            - MongoDB 数据库:
                - v0.7.0: openapi/mcamel/mongodb/mongodb-v0.7.0.md
                - v0.6.0: openapi/mcamel/mongodb/mongodb-v0.6.0.md
                - v0.5.0: openapi/mcamel/mongodb/mongodb-v0.5.0.md
                - v0.4.0: openapi/mcamel/mongodb/mongodb-v0.4.0.md
                - v0.3.x:
                    - v0.3.0: openapi/mcamel/mongodb/mongodb-v0.3.0.md
                    - v0.3.1: openapi/mcamel/mongodb/mongodb-v0.3.1.md
                - v0.2.0: openapi/mcamel/mongodb/mongodb-v0.2.0.md
                - v0.1.0: openapi/mcamel/mongodb/mongodb-v0.1.0.md
            - MySQL 数据库:
                - v0.15.0: openapi/mcamel/mysql/mysql-v0.15.0.md
                - v0.14.0: openapi/mcamel/mysql/mysql-v0.14.0.md
                - v0.13.0: openapi/mcamel/mysql/mysql-v0.13.0.md
                - v0.12.0: openapi/mcamel/mysql/mysql-v0.12.0.md
                - v0.11.x:
                    - v0.11.0: openapi/mcamel/mysql/mysql-v0.11.0.md
                    - v0.11.1: openapi/mcamel/mysql/mysql-v0.11.1.md
                - v0.10.x:
                    - v0.10.0: openapi/mcamel/mysql/mysql-v0.10.0.md
                    - v0.10.1: openapi/mcamel/mysql/mysql-v0.10.1.md
                    - v0.10.2: openapi/mcamel/mysql/mysql-v0.10.2.md
                    - v0.10.3: openapi/mcamel/mysql/mysql-v0.10.3.md
                - v0.9.0: openapi/mcamel/mysql/mysql-v0.9.0.md
                - v0.8.x:
                    - v0.8.0: openapi/mcamel/mysql/mysql-v0.8.0.md
                    - v0.8.1: openapi/mcamel/mysql/mysql-v0.8.1.md
            - PostgreSQL 数据库:
                - v0.9.0: openapi/mcamel/postgresql/postgresql-v0.9.0.md
                - v0.8.0: openapi/mcamel/postgresql/postgresql-v0.8.0.md
                - v0.7.0: openapi/mcamel/postgresql/postgresql-v0.7.0.md
                - v0.6.0: openapi/mcamel/postgresql/postgresql-v0.6.0.md
                - v0.5.x:
                    - v0.5.0: openapi/mcamel/postgresql/postgresql-v0.5.0.md
                    - v0.5.1: openapi/mcamel/postgresql/postgresql-v0.5.1.md
                - v0.4.0: openapi/mcamel/postgresql/postgresql-v0.4.0.md
                - v0.3.0: openapi/mcamel/postgresql/postgresql-v0.3.0.md
                - v0.2.0: openapi/mcamel/postgresql/postgresql-v0.2.0.md
                - v0.1.x:
                    - v0.1.0: openapi/mcamel/postgresql/postgresql-v0.1.0.md
                    - v0.1.1: openapi/mcamel/postgresql/postgresql-v0.1.1.md
                    - v0.1.2: openapi/mcamel/postgresql/postgresql-v0.1.2.md
            - Redis 缓存服务:
                - v0.15.0: openapi/mcamel/redis/redis-v0.15.0.md
                - v0.14.0: openapi/mcamel/redis/redis-v0.14.0.md
                - v0.13.0: openapi/mcamel/redis/redis-v0.13.0.md
                - v0.11.x:
                    - v0.11.0: openapi/mcamel/redis/redis-v0.11.0.md
                    - v0.11.1: openapi/mcamel/redis/redis-v0.11.1.md
                - v0.10.0: openapi/mcamel/redis/redis-v0.10.0.md
                - v0.9.0: openapi/mcamel/redis/redis-v0.9.0.md
                - v0.8.0: openapi/mcamel/redis/redis-v0.8.0.md
                - v0.7.x:
                    - v0.7.0: openapi/mcamel/redis/redis-v0.7.0.md
                    - v0.7.1: openapi/mcamel/redis/redis-v0.7.1.md
                    - v0.7.2: openapi/mcamel/redis/redis-v0.7.2.md
                    - v0.7.3: openapi/mcamel/redis/redis-v0.7.3.md     
        - 云边协同 OpenAPI:
            - v0.8.0: openapi/kant/v0.8.0.md
        - 全局管理 OpenAPI:
            - v0.24.x:
                - v0.24.0: openapi/ghippo/v0.24.0.md
                - v0.24.1: openapi/ghippo/v0.24.1.md
            - v0.23.x:
                - v0.23.0: openapi/ghippo/v0.23.0.md
                - v0.23.1: openapi/ghippo/v0.23.1.md
            - v0.22.1: openapi/ghippo/v0.22.1.md
            - v0.21.0: openapi/ghippo/v0.21.0.md
            - v0.20.x:
                - v0.20.0: openapi/ghippo/v0.20.0.md
                - v0.20.1: openapi/ghippo/v0.20.1.md
            - v0.19.0: openapi/ghippo/v0.19.0.md
            - v0.18.x:
                - v0.18.0: openapi/ghippo/v0.18.0.md
                - v0.18.1: openapi/ghippo/v0.18.1.md
            - v0.17.x:
                - v0.17.0: openapi/ghippo/v0.17.0.md
                - v0.17.1: openapi/ghippo/v0.17.1.md
            - v0.16.x:
                - v0.16.0: openapi/ghippo/v0.16.0.md
                - v0.16.1: openapi/ghippo/v0.16.1.md
            - v0.15.0: openapi/ghippo/v0.15.0.md