nav:
    - OpenAPI 文档:
        - OpenAPI 文档索引: openapi/index.md
        - 全局管理 OpenAPI:
            - v0.15.0: openapi/ghippo/v0.15.0.md
            - v0.16.0: openapi/ghippo/v0.16.0.md
            - v0.16.1: openapi/ghippo/v0.16.1.md
        - 服务网格 OpenAPI: openapi/mspider/v0.105.1.md
        - 可观测性 OpenAPI: openapi/insight/v0.16.0.md
        - 多云编排 OpenAPI: openapi/kairship/v0.8.0.md
        - 网络 OpenAPI: 
            - v0.5.0: openapi/spidernet/v0.5.0.md
            - v0.6.0: openapi/spidernet/v0.6.0.md
        - 中间件 OpenAPI: 
            - Index: openapi/midware.md
            - Elasticsearch OpenAPI:
                - v0.7.0: openapi/mcamel/elasticsearch-v0.7.0.md
                - v0.7.1: openapi/mcamel/elasticsearch-v0.7.1.md
            - Kafka OpenAPI:
                - v0.5.0: openapi/mcamel/kafka-v0.5.0.md
                - v0.5.1: openapi/mcamel/kafka-v0.5.1.md
            - MinIO OpenAPI: 
                - v0.5.0: openapi/mcamel/minio-v0.5.0.md
                - v0.5.1: openapi/mcamel/minio-v0.5.1.md
            - MySQL OpenAPI: 
                - v0.8.0: openapi/mcamel/mysql-v0.8.0.md
                - v0.8.1: openapi/mcamel/mysql-v0.8.1.md
            - PostgreSQL OpenAPI: 
                - v0.1.0: openapi/mcamel/postgresql-v0.1.0.md
                - v0.1.1: openapi/mcamel/postgresql-v0.1.1.md
                - v0.1.2: openapi/mcamel/postgresql-v0.1.2.md
            - RabbitMQ OpenAPI: 
                - v0.10.0: openapi/mcamel/rabbitmq-v0.10.0.md
                - v0.10.1: openapi/mcamel/rabbitmq-v0.10.1.md
            - Redis OpenAPI: 
                - v0.7.0: openapi/mcamel/redis-v0.7.0.md
                - v0.7.1: openapi/mcamel/redis-v0.7.1.md